# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sendData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esendData.proto\x12\x08senddata\"(\n\x0c\x44\x65viceNumber\x12\x18\n\x10number_displayed\x18\x01 \x01(\x05\"\x1b\n\x06\x44\x65vice\x12\x11\n\tdevice_id\x18\x01 \x01(\x05\x32\xb3\x02\n\x08SendData\x12\x41\n\x0fGetDeviceNumber\x12\x10.senddata.Device\x1a\x16.senddata.DeviceNumber\"\x00(\x01\x30\x01\x12\x42\n\x16GetRobotPointingDevice\x12\x10.senddata.Device\x1a\x10.senddata.Device\"\x00(\x01\x30\x01\x12\x34\n\x06GetFoo\x12\x10.senddata.Device\x1a\x16.senddata.DeviceNumber\"\x00\x12\x31\n\x07GetFoo2\x12\x10.senddata.Device\x1a\x10.senddata.Device\"\x00(\x01\x12\x37\n\x07GetFoo3\x12\x10.senddata.Device\x1a\x16.senddata.DeviceNumber\"\x00\x30\x01\x42\'\n\x14server.gRpc.senddataB\x08SendDataP\x01\xa2\x02\x02SDb\x06proto3')



_DEVICENUMBER = DESCRIPTOR.message_types_by_name['DeviceNumber']
_DEVICE = DESCRIPTOR.message_types_by_name['Device']
DeviceNumber = _reflection.GeneratedProtocolMessageType('DeviceNumber', (_message.Message,), {
  'DESCRIPTOR' : _DEVICENUMBER,
  '__module__' : 'sendData_pb2'
  # @@protoc_insertion_point(class_scope:senddata.DeviceNumber)
  })
_sym_db.RegisterMessage(DeviceNumber)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'sendData_pb2'
  # @@protoc_insertion_point(class_scope:senddata.Device)
  })
_sym_db.RegisterMessage(Device)

_SENDDATA = DESCRIPTOR.services_by_name['SendData']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024server.gRpc.senddataB\010SendDataP\001\242\002\002SD'
  _DEVICENUMBER._serialized_start=28
  _DEVICENUMBER._serialized_end=68
  _DEVICE._serialized_start=70
  _DEVICE._serialized_end=97
  _SENDDATA._serialized_start=100
  _SENDDATA._serialized_end=407
# @@protoc_insertion_point(module_scope)
